### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by tok-kkk** [renproject/lightnode#52]
We want to improve test coverage for each package and have an integration test for the whole lightnode. Tests should be integrated into our existing CI and triggered by every new commit. 
Since lightnode is the main int user interact with 

## Tests

- [ ] Tests should check the error message is meaningful when the input is invalid or something goes wrong.
- [ ] Benchmarking (use a top-level integration test that floods the Lightnode with many parallel requests).
- [ ] Fuzzing (random bytes)
- [ ] Fuzzing (random JSON)
- [ ] Fuzzing (random well-formed but invalid requests)
- [ ] Ensure that every package has some level of testing
- [ ] Improve top-level integration testing
- [ ] Trying to aim for 80%+ test coverage.

## CI 

- [ ] Use GitHub Actions to run all tests and report test coverage.
- [ ] Update the badges in the README.md file.

**Comment by jazg** [comment]
Closing as this issue is outdated.
