### ISSUE TITLE
Support for transaction tagging

### ISSUE THREAD

**Issue by loongy** [renproject/lightnode#63]
Currently, there is no way to query transactions by any kind of application-specific or use-case-specific  data. The only possibility is querying transactions by status. Ideally, RenVM is able to support user flows where the user is identified in an arbitrary way (this allows maximum flexibility between both chains and use-cases) and can query their transactions.

## Design

This issue proposes the addition of an optional `”tags”` parameter in the `”ren_submitTx”` and `”ren_queryTxs”` methods. These tags are considered indices for the transaction, and transactions can be looked up using these tags (`”ren_queryTx”` will filter by the tags when the parameter is present).

This optional parameter is intentionally malleable (it can be modified during gossiping throughout the peer network), because different nodes might want to index transactions differently, and we do not want to force nodes to respect the index. In this sense, the only sensible way to use tags is when interacting with a trusted Lightnode (either one that is owned, or one that is managed by a trusted API provider like the Ren team). Note: using tags with untrusted Lightnodes is not a security concern, it just provides no guarantees that the tag will be respected.

### Multiples

We should implement this using `”tags”: []` not `”tag”` and let nodes decide what the maximum number of supported tags are. Default to 1 is essentially the same as only supporting `”tag”`, but it is future compatible with supporting multiple tags if that becomes needed.

### Pagination

A direct consequence of having an optional tags is pagination and ordering. The `”ren_queryTxs”` currently requires no specific ordering. This needs to be changed such that transactions are ordered by their transaction hashes (given that most storage will already be indexing by this value, it is the least intrusive one to order by). We also need to include optional `”page”` and `”pageSize”` parameters (where each node supports their own maximum page size limit). The `”page”` tells the node to skip the first `page*pageSize` number of transactions. The `”pageSize”` is the maximum number of transactions to return. Returning 0 transactions implies there are no more pages. 

### Hosted Lightnodes

The hosted Lightnodes managed by the Ren team will respect tags. We will default to a maximum of 1 tag for now, and if there is evidence of need for more, we will reconsider this limit. Pages will be limited to 10 transactions.

### Darknodes

Darknodes will no respect any tags. This minimises their resource requirements.

## Implementation

- [x] Add the `”ren_queryTxs”` method.
- [x] Add an optional `”tags”` parameter time `”ren_submitTx”` and `”ren_queryTxs”`. It must be an arbitrary list of 32-byte hashes.
- [x] Add optional `”page”` and `”pageSize”` (both integers) to `”ren_queryTxs”`. Negative values should be clamped to zero.
- [x] Add an option to the JSON-RPC 2.0 server to limit number of `”tags”` supported and maximum `”pageSize”` (default to one).
- [x] Add `”tag0”` as a column to the Lightnode SQL database.
- [x] Support `SELECT * WHERE tag0 =` type queries against the database when resolving content for the `”ren_queryTxs”` method.
- [ ] Require `”ren_queryTxs”` to return transactions ordered by hash only when the pagination parameters are present. At all other times, transactions can be returned in any order (ordering is only important because of pagination).

**Comment by jazg** [comment]
Transactions are ordered by date created, but the rest of the implementation details have been addressed by #68.

**Comment by Nandiin** [comment]
What's the status of this feature?

I submitted a mint to renVM via `ren-js` with 
`tags: ['Zm9vLTB4OTM5OWI5NjZjRDZFOTFiQzE4MTg3NjEyNDY0OEJCMmQ4RjcyQTQ5OA==']`
and the returned `txHash` is `Oq4Y+R9KFpB56pBTKhTFvzn9KbGiZQ1GpTmktiZcX8g=`

The transaction can be found with its `txHash` via `ren_queryTx` method but using `ren_queryTxs` with parameter `{ tag: ['Zm9vLTB4OTM5OWI5NjZjRDZFOTFiQzE4MTg3NjEyNDY0OEJCMmQ4RjcyQTQ5OA=='] }` returns an empty array.

I suspect `tags` field is not respected as I cant find it even in the reponse of `ren_queryTx`.

![image](https://user-images.githubusercontent.com/10903833/94663182-f26b3c80-033b-11eb-9ee2-a8dab109ad31.png)

![image](https://user-images.githubusercontent.com/10903833/94663192-f4350000-033b-11eb-8f63-97b0b419a225.png)

**Comment by Nandiin** [comment]
Another question for this `ren_queryTxs` method is what type of value should be provided for the `status` field ?

Using a plain string results in a 400 response.

![image](https://user-images.githubusercontent.com/10903833/94663966-e16efb00-033c-11eb-8a9a-4ec0099999f5.png)

**Comment by jazg** [comment]
@Nandiin Apologies for the late response. The tags are expected to be 32 bytes, which is most likely the reason your query fails. Regarding the `txStatus` field, unfortunately I don't believe it is being respected right now.

I'll close this issue for now as we're currently working on an improved Lightnode, in which we may look at a simplified querying/tagging system. If you have any other questions or suggestions, please feel free to let us know.
